### ISSUE TITLE
Add CI?

### ISSUE THREAD

**Issue by mkinney** [meshtastic/api#3]
Can a CI of some sort be added?

Perhaps something like this?

```
# Test with latest node version
image: node:latest

# Cache dependencies
cache:
  paths:
    - node_modules/

# Run unit tests
test:
  script:
    # Install
    - yarn
    # Run Jest in CI mode
    - yarn test --ci
 ```

Source: https://dev.to/shelob9/gitlab-ci-for-a-typescript-project-bootstrapped-with-tsdx-4nle
